//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlagSolverLibrary {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlagSolverLibrary.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{&quot;Block_rashet&quot;:1,&quot;Glinozem&quot;:12,&quot;Id&quot;:1,&quot;K_MgO&quot;:5,&quot;Nomer_rashet&quot;:1,&quot;Temperature&quot;:1400,&quot;x&quot;:0.8,&quot;y&quot;:11},{&quot;Block_rashet&quot;:1,&quot;Glinozem&quot;:12,&quot;Id&quot;:2,&quot;K_MgO&quot;:5,&quot;Nomer_rashet&quot;:1,&quot;Temperature&quot;:1400,&quot;x&quot;:0.9,&quot;y&quot;:11},{&quot;Block_rashet&quot;:1,&quot;Glinozem&quot;:12,&quot;Id&quot;:3,&quot;K_MgO&quot;:5,&quot;Nomer_rashet&quot;:1,&quot;Temperature&quot;:1400,&quot;x&quot;:1,&quot;y&quot;:8},{&quot;Block_rashet&quot;:1,&quot;Glinozem&quot;:12,&quot;Id&quot;:4,&quot;K_MgO&quot;:5,&quot;Nomer_rashet&quot;:1,&quot;Temperature&quot;:1400,&quot;x&quot;:1.07,&quot;y&quot;:7.5},{&quot;Block_rashet&quot;:1,&quot;Glinozem&quot;:12,&quot;Id&quot;:5,&quot;K_MgO&quot;:5,&quot;Nomer_rashet&quot;:1,&quot;Temperature&quot;:1400,&quot;x&quot;:1.15,&quot;y&quot;:7},{&quot;Block [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string JsonDatabaseString {
            get {
                return ResourceManager.GetString("JsonDatabaseString", resourceCulture);
            }
        }
    }
}
