// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SlagModeServer.Services;

#nullable disable

namespace SlagModeServer.Migrations
{
    [DbContext(typeof(SlagSolverDbContext))]
    partial class SlagSolverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SlagModeServer.entities.NewStructure.BlastFurnaces", b =>
                {
                    b.Property<int>("FurnaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FurnaceID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FurnaceID");

                    b.ToTable("BlastFurnaces");

                    b.HasData(
                        new
                        {
                            FurnaceID = 1,
                            Name = "TestBF"
                        });
                });

            modelBuilder.Entity("SlagModeServer.entities.NewStructure.ShihtaCatalog", b =>
                {
                    b.Property<int>("ComponentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentID"));

                    b.Property<double>("Al2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("CaO")
                        .HasColumnType("double precision");

                    b.Property<double>("Cr")
                        .HasColumnType("double precision");

                    b.Property<double>("Fe")
                        .HasColumnType("double precision");

                    b.Property<double>("Fe2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("FeO")
                        .HasColumnType("double precision");

                    b.Property<double>("H2O")
                        .HasColumnType("double precision");

                    b.Property<double>("MgO")
                        .HasColumnType("double precision");

                    b.Property<double>("MnO")
                        .HasColumnType("double precision");

                    b.Property<string>("NameShihta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Pmpp")
                        .HasColumnType("double precision");

                    b.Property<string>("RuNameShihta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("S")
                        .HasColumnType("double precision");

                    b.Property<double>("SiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("TiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("Zn")
                        .HasColumnType("double precision");

                    b.HasKey("ComponentID");

                    b.ToTable("ChargeCatalogs");

                    b.HasData(
                        new
                        {
                            ComponentID = 1,
                            Al2O3 = 1.75,
                            CaO = 8.7200000000000006,
                            Cr = 0.0,
                            Fe = 58.5,
                            Fe2O3 = 0.0,
                            FeO = 0.0,
                            H2O = 0.0,
                            MgO = 1.6299999999999999,
                            MnO = 0.19,
                            NameShihta = "Agglomerate23",
                            Pmpp = 0.0,
                            RuNameShihta = "агломерат а/ф № 2 и 3",
                            S = 0.028000000000000001,
                            SiO2 = 5.8799999999999999,
                            TiO2 = 0.23999999999999999,
                            Zn = 0.0
                        },
                        new
                        {
                            ComponentID = 2,
                            Al2O3 = 1.76,
                            CaO = 8.8599999999999994,
                            Cr = 0.0,
                            Fe = 58.299999999999997,
                            Fe2O3 = 0.0,
                            FeO = 0.0,
                            H2O = 0.0,
                            MgO = 1.6399999999999999,
                            MnO = 0.19,
                            NameShihta = "Agglomerate4",
                            Pmpp = 0.0,
                            RuNameShihta = "агломерат а/ф № 4",
                            S = 0.028000000000000001,
                            SiO2 = 5.9500000000000002,
                            TiO2 = 0.23999999999999999,
                            Zn = 0.0
                        },
                        new
                        {
                            ComponentID = 3,
                            Al2O3 = 1.21,
                            CaO = 4.0199999999999996,
                            Cr = 0.0,
                            Fe = 62.600000000000001,
                            Fe2O3 = 0.0,
                            FeO = 0.0,
                            H2O = 0.0,
                            MgO = 0.98999999999999999,
                            MnO = 0.16,
                            NameShihta = "Ssgpo",
                            Pmpp = 0.0,
                            RuNameShihta = "окатыши ССГПО",
                            S = 0.067000000000000004,
                            SiO2 = 3.7000000000000002,
                            TiO2 = 0.32000000000000001,
                            Zn = 0.0
                        },
                        new
                        {
                            ComponentID = 4,
                            Al2O3 = 0.25,
                            CaO = 0.40000000000000002,
                            Cr = 0.0,
                            Fe = 65.700000000000003,
                            Fe2O3 = 0.0,
                            FeO = 0.0,
                            H2O = 0.0,
                            MgO = 0.22,
                            MnO = 0.050000000000000003,
                            NameShihta = "Lebedinskiy",
                            Pmpp = 0.0,
                            RuNameShihta = "ЛебГОК",
                            S = 0.01,
                            SiO2 = 5.1699999999999999,
                            TiO2 = 0.0,
                            Zn = 0.0
                        },
                        new
                        {
                            ComponentID = 5,
                            Al2O3 = 2.5899999999999999,
                            CaO = 1.28,
                            Cr = 0.0,
                            Fe = 60.399999999999999,
                            Fe2O3 = 0.0,
                            FeO = 0.0,
                            H2O = 0.0,
                            MgO = 2.8999999999999999,
                            MnO = 0.23000000000000001,
                            NameShihta = "Kachkanarsiy",
                            Pmpp = 0.0,
                            RuNameShihta = "КачГОК",
                            S = 0.02,
                            SiO2 = 4.3600000000000003,
                            TiO2 = 2.6600000000000001,
                            Zn = 0.0
                        },
                        new
                        {
                            ComponentID = 6,
                            Al2O3 = 0.23000000000000001,
                            CaO = 1.49,
                            Cr = 0.0,
                            Fe = 63.299999999999997,
                            Fe2O3 = 0.0,
                            FeO = 0.0,
                            H2O = 0.0,
                            MgO = 0.25,
                            MnO = 0.040000000000000001,
                            NameShihta = "Mixailovskiy",
                            Pmpp = 0.0,
                            RuNameShihta = "МихГОК ",
                            S = 0.01,
                            SiO2 = 7.25,
                            TiO2 = 0.0,
                            Zn = 0.0
                        },
                        new
                        {
                            ComponentID = 7,
                            Al2O3 = 0.73999999999999999,
                            CaO = 0.25,
                            Cr = 0.0,
                            Fe = 69.799999999999997,
                            Fe2O3 = 0.0,
                            FeO = 0.0,
                            H2O = 0.0,
                            MgO = 0.39000000000000001,
                            MnO = 0.83999999999999997,
                            NameShihta = "WeldSlag",
                            Pmpp = 0.0,
                            RuNameShihta = "Сварочный шлак",
                            S = 0.02,
                            SiO2 = 4.2999999999999998,
                            TiO2 = 0.0,
                            Zn = 0.0
                        },
                        new
                        {
                            ComponentID = 8,
                            Al2O3 = 2.0,
                            CaO = 8.5,
                            Cr = 0.0,
                            Fe = 68.400000000000006,
                            Fe2O3 = 0.0,
                            FeO = 0.0,
                            H2O = 0.0,
                            MgO = 3.1000000000000001,
                            MnO = 0.97999999999999998,
                            NameShihta = "MinimalIncludes",
                            Pmpp = 0.0,
                            RuNameShihta = "Королёк",
                            S = 0.11,
                            SiO2 = 6.7999999999999998,
                            TiO2 = 0.34000000000000002,
                            Zn = 0.0
                        });
                });

            modelBuilder.Entity("SlagModeServer.entities.NewStructure.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Login = "Login",
                            Password = "Password"
                        });
                });

            modelBuilder.Entity("SlagModeServer.entities.NewStructure.VariantCharges", b =>
                {
                    b.Property<int>("VariantID")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentID")
                        .HasColumnType("integer");

                    b.Property<double>("Consumption")
                        .HasColumnType("double precision");

                    b.Property<double>("Fe2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaAl2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaCaO")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaCr")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaFe")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaFeO")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaH2O")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaMgO")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaMnO")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaP")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaPmpp")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaS")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaSiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaTiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaType")
                        .HasColumnType("double precision");

                    b.Property<double>("ShihtaZn")
                        .HasColumnType("double precision");

                    b.HasKey("VariantID", "ComponentID");

                    b.HasIndex("ComponentID");

                    b.HasIndex("VariantID", "ComponentID");

                    b.ToTable("VariantCharges");

                    b.HasData(
                        new
                        {
                            VariantID = 1,
                            ComponentID = 1,
                            Consumption = 441.5,
                            Fe2O3 = 0.0,
                            ShihtaAl2O3 = 1.75,
                            ShihtaCaO = 8.7200000000000006,
                            ShihtaCr = 0.0,
                            ShihtaFe = 58.5,
                            ShihtaFeO = 0.0,
                            ShihtaH2O = 0.0,
                            ShihtaMgO = 1.6299999999999999,
                            ShihtaMnO = 0.19,
                            ShihtaP = 0.0,
                            ShihtaPmpp = 0.0,
                            ShihtaS = 0.028000000000000001,
                            ShihtaSiO2 = 5.8799999999999999,
                            ShihtaTiO2 = 0.23999999999999999,
                            ShihtaType = 0.0,
                            ShihtaZn = 0.0
                        },
                        new
                        {
                            VariantID = 1,
                            ComponentID = 2,
                            Consumption = 485.89999999999998,
                            Fe2O3 = 0.0,
                            ShihtaAl2O3 = 1.76,
                            ShihtaCaO = 8.8599999999999994,
                            ShihtaCr = 0.0,
                            ShihtaFe = 58.299999999999997,
                            ShihtaFeO = 0.0,
                            ShihtaH2O = 0.0,
                            ShihtaMgO = 1.6399999999999999,
                            ShihtaMnO = 0.19,
                            ShihtaP = 0.0,
                            ShihtaPmpp = 0.0,
                            ShihtaS = 0.028000000000000001,
                            ShihtaSiO2 = 5.9500000000000002,
                            ShihtaTiO2 = 0.23999999999999999,
                            ShihtaType = 0.0,
                            ShihtaZn = 0.0
                        },
                        new
                        {
                            VariantID = 1,
                            ComponentID = 3,
                            Consumption = 568.70000000000005,
                            Fe2O3 = 0.0,
                            ShihtaAl2O3 = 1.21,
                            ShihtaCaO = 4.0199999999999996,
                            ShihtaCr = 0.0,
                            ShihtaFe = 62.600000000000001,
                            ShihtaFeO = 0.0,
                            ShihtaH2O = 0.0,
                            ShihtaMgO = 0.98999999999999999,
                            ShihtaMnO = 0.16,
                            ShihtaP = 0.0,
                            ShihtaPmpp = 0.0,
                            ShihtaS = 0.067000000000000004,
                            ShihtaSiO2 = 3.7000000000000002,
                            ShihtaTiO2 = 0.32000000000000001,
                            ShihtaType = 0.0,
                            ShihtaZn = 0.0
                        },
                        new
                        {
                            VariantID = 1,
                            ComponentID = 4,
                            Consumption = 54.700000000000003,
                            Fe2O3 = 0.0,
                            ShihtaAl2O3 = 0.25,
                            ShihtaCaO = 0.40000000000000002,
                            ShihtaCr = 0.0,
                            ShihtaFe = 65.700000000000003,
                            ShihtaFeO = 0.0,
                            ShihtaH2O = 0.0,
                            ShihtaMgO = 0.22,
                            ShihtaMnO = 0.050000000000000003,
                            ShihtaP = 0.0,
                            ShihtaPmpp = 0.0,
                            ShihtaS = 0.01,
                            ShihtaSiO2 = 5.1699999999999999,
                            ShihtaTiO2 = 0.0,
                            ShihtaType = 0.0,
                            ShihtaZn = 0.0
                        },
                        new
                        {
                            VariantID = 1,
                            ComponentID = 5,
                            Consumption = 54.100000000000001,
                            Fe2O3 = 0.0,
                            ShihtaAl2O3 = 2.5899999999999999,
                            ShihtaCaO = 1.28,
                            ShihtaCr = 0.0,
                            ShihtaFe = 60.399999999999999,
                            ShihtaFeO = 0.0,
                            ShihtaH2O = 0.0,
                            ShihtaMgO = 2.8999999999999999,
                            ShihtaMnO = 0.23000000000000001,
                            ShihtaP = 0.0,
                            ShihtaPmpp = 0.0,
                            ShihtaS = 0.02,
                            ShihtaSiO2 = 4.3600000000000003,
                            ShihtaTiO2 = 2.6600000000000001,
                            ShihtaType = 0.0,
                            ShihtaZn = 0.0
                        },
                        new
                        {
                            VariantID = 1,
                            ComponentID = 6,
                            Consumption = 48.5,
                            Fe2O3 = 0.0,
                            ShihtaAl2O3 = 0.23000000000000001,
                            ShihtaCaO = 1.49,
                            ShihtaCr = 0.0,
                            ShihtaFe = 63.299999999999997,
                            ShihtaFeO = 0.0,
                            ShihtaH2O = 0.0,
                            ShihtaMgO = 0.25,
                            ShihtaMnO = 0.040000000000000001,
                            ShihtaP = 0.0,
                            ShihtaPmpp = 0.0,
                            ShihtaS = 0.01,
                            ShihtaSiO2 = 7.25,
                            ShihtaTiO2 = 0.0,
                            ShihtaType = 0.0,
                            ShihtaZn = 0.0
                        });
                });

            modelBuilder.Entity("SlagModeServer.entities.NewStructure.VariantsParameter", b =>
                {
                    b.Property<int>("VariantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VariantID"));

                    b.Property<int>("BlastFurnaceID")
                        .HasColumnType("integer");

                    b.Property<double>("BlowMoisture")
                        .HasColumnType("double precision");

                    b.Property<double>("BlowO2")
                        .HasColumnType("double precision");

                    b.Property<double>("BlowPressure")
                        .HasColumnType("double precision");

                    b.Property<double>("BlowTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("CokeAsh")
                        .HasColumnType("double precision");

                    b.Property<double>("CokeAshAl2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("CokeAshCaO")
                        .HasColumnType("double precision");

                    b.Property<double>("CokeAshFe")
                        .HasColumnType("double precision");

                    b.Property<double>("CokeAshMgO")
                        .HasColumnType("double precision");

                    b.Property<double>("CokeAshP")
                        .HasColumnType("double precision");

                    b.Property<double>("CokeAshSiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("CokeConsumption")
                        .HasColumnType("double precision");

                    b.Property<double>("CokeS")
                        .HasColumnType("double precision");

                    b.Property<double>("CokeVolatile")
                        .HasColumnType("double precision");

                    b.Property<string>("DateVariant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DustRemoval")
                        .HasColumnType("double precision");

                    b.Property<double>("IronC")
                        .HasColumnType("double precision");

                    b.Property<double>("IronMn")
                        .HasColumnType("double precision");

                    b.Property<double>("IronP")
                        .HasColumnType("double precision");

                    b.Property<double>("IronProduction")
                        .HasColumnType("double precision");

                    b.Property<double>("IronS")
                        .HasColumnType("double precision");

                    b.Property<double>("IronSi")
                        .HasColumnType("double precision");

                    b.Property<double>("IronTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("IronTi")
                        .HasColumnType("double precision");

                    b.Property<double>("NaturalGasConsumption")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagAl2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagCaO")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagMgO")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagOutput")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagS")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagSiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagTiO2")
                        .HasColumnType("double precision");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("VariantName")
                        .HasColumnType("text");

                    b.HasKey("VariantID");

                    b.HasIndex("BlastFurnaceID");

                    b.HasIndex("UserID", "BlastFurnaceID");

                    b.ToTable("VariantsParameters");

                    b.HasData(
                        new
                        {
                            VariantID = 1,
                            BlastFurnaceID = 1,
                            BlowMoisture = 0.0,
                            BlowO2 = 0.0,
                            BlowPressure = 0.0,
                            BlowTemperature = 0.0,
                            CokeAsh = 12.699999999999999,
                            CokeAshAl2O3 = 24.600000000000001,
                            CokeAshCaO = 7.7999999999999998,
                            CokeAshFe = 0.0,
                            CokeAshMgO = 2.0,
                            CokeAshP = 0.0,
                            CokeAshSiO2 = 48.100000000000001,
                            CokeConsumption = 419.80000000000001,
                            CokeS = 0.42799999999999999,
                            CokeVolatile = 0.0,
                            DateVariant = "2024-07-25 12:07:00",
                            DustRemoval = 0.0,
                            IronC = 4.702,
                            IronMn = 0.20000000000000001,
                            IronP = 0.0,
                            IronProduction = 0.0,
                            IronS = 0.016,
                            IronSi = 0.51200000000000001,
                            IronTemperature = 1450.0,
                            IronTi = 0.0,
                            NaturalGasConsumption = 0.0,
                            SlagAl2O3 = 11.43,
                            SlagCaO = 40.899999999999999,
                            SlagMgO = 7.3920000000000003,
                            SlagOutput = 0.0,
                            SlagS = 0.0,
                            SlagSiO2 = 36.560000000000002,
                            SlagTiO2 = 0.01,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("SlagModeServer.entities.NewStructure.VariantCharges", b =>
                {
                    b.HasOne("SlagModeServer.entities.NewStructure.ShihtaCatalog", "CatalogElem")
                        .WithMany()
                        .HasForeignKey("ComponentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlagModeServer.entities.NewStructure.VariantsParameter", "VariantParameters")
                        .WithMany()
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogElem");

                    b.Navigation("VariantParameters");
                });

            modelBuilder.Entity("SlagModeServer.entities.NewStructure.VariantsParameter", b =>
                {
                    b.HasOne("SlagModeServer.entities.NewStructure.BlastFurnaces", "BlastFurnace")
                        .WithMany()
                        .HasForeignKey("BlastFurnaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlagModeServer.entities.NewStructure.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlastFurnace");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
